# Generated by Django 5.0.6 on 2024-07-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geminii', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
